### ISSUE TITLE
Received value not suitable for type Numeric (float)

### ISSUE THREAD

**Issue by nemd** [wawastein/zabbix-cloudwatch#10]
Discovery works - I can see objects (like S3 buckets) but there are no values and on item list I can see that all of them have not supported status with error as below:

`` 
Received value [Traceback (most recent call last): File "./cloudwatch.metric", line 94, in <module> dimensions=dimensions) File "./cloudwatch.metric", line 20, in get_metric Period=interval) File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call return self._make_api_call(operation_name, kwargs) File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 612, in _make_api_call raise error_class(parsed_response, operation_name)botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the GetMetricStatistics operation: Signature not yet current: 20180307T081832Z is still later than 20180307T081739Z (20180307T081239Z + 5 min.)] is not suitable for value type [Numeric (float)]``

**Comment by wawastein** [comment]
@nemd check this out: https://forums.aws.amazon.com/thread.jspa?threadID=103764

**Comment by nemd** [comment]
yes, that was the issue. After setting correct time with ntp problem is gone and everything works. Thanks @wawastein
