### ISSUE TITLE
error: interval is required

### ISSUE THREAD

**Issue by jashankochar** [wawastein/zabbix-cloudwatch#11]
![image](https://user-images.githubusercontent.com/17452611/39994276-6e1c1178-5796-11e8-9d1d-45fd879c5e72.png)

Am passing the same keys as in template but getting above eror

**Comment by wawastein** [comment]
Obviously, as it says, problem is in missing --interval argument. I'd like to see how this particular item is configured on your side.

**Comment by jashankochar** [comment]
Hey it was due to wrong file call under scripts. My bad.
