### ISSUE TITLE
S3 bucket has no data points (all buckets)

### ISSUE THREAD

**Issue by dragan979** [wawastein/zabbix-cloudwatch#14]
For all buckets i get "no data points" and values for all buckets is -1, when i change trigger values to different than -1 alert remains

```
{Cloudwatch Template:cloudwatch.metric[600,BucketSizeBytes,AWS/S3,Average,{$REGION},"BucketName={#BUCKET_NAME},StorageType=StandardStorage",{$ACCOUNT}].last()}<>-1 or
{Cloudwatch Template:cloudwatch.metric[600,NumberOfObjects,AWS/S3,Average,{$REGION},"BucketName={#BUCKET_NAME},StorageType=AllStorageTypes",{$ACCOUNT}].last()}<>-1
```

**Comment by wawastein** [comment]
Did you test it from terminal first? Get all required parameters (region, bucket name) and run script manually, maybe you'll catch something.Try different periods (larger than 600 sec) too.

**Comment by dragan979** [comment]
believed it or not- solved issues by un-linking and clearing template and then re-assigning it back
now all works fine, thanks for great job !!
