### ISSUE TITLE
Multiple AWS zones

### ISSUE THREAD

**Issue by dragan979** [wawastein/zabbix-cloudwatch#15]
![1](https://user-images.githubusercontent.com/29802460/43404126-108e7b1e-9417-11e8-9eb7-2a8d241632e4.PNG)

![2](https://user-images.githubusercontent.com/29802460/43404207-363016c0-9417-11e8-9bb2-49ae665c8597.PNG)

But, instead of EC2 instances from both regions i got only instances from us-east-1 duplicated

**Comment by wawastein** [comment]
1. It was designed in a way, that each region acts as its own Zabbix host. So you can create host Virginia and set REGION to us-east-1, and another corresponding to Ireland.
2. If you want to put everything into one host, you need to modify discovery rule first. Item prototypes work with what discovery rule returned. I'm not sure you can grab 2 regions with one rule, it would be a pain to configure, but if you're willing to do that - you're free to modify it any way you want

**Comment by dragan979** [comment]
aha, ok , thanks for clarification
