### ISSUE TITLE
Import cloudwatch_template.xml failed

### ISSUE THREAD

**Issue by melch700** [wawastein/zabbix-cloudwatch#20]
zabbix 4.0 lts

when i import the cloudwatch_template.xml i get the following error

Invalid key "instances[{#TARGET_GROUP_LOAD_BALANCER_NAME}][{#TARGET_GROUP_NAME}]" for item prototype "ELBv2: {#TARGET_GROUP_LOAD_BALANCER_NAME} target group {#TARGET_GROUP_NAME} total targets" on "Cloudwatch Template": incorrect syntax near "[{#TARGET_GROUP_NAME}]".

**Comment by danimas** [comment]
Same error here on zabbix 4.2

**Comment by MrBal** [comment]
@danimas and @melch700 try like this
<"key>instances[{#TARGET_GROUP_LOAD_BALANCER_NAME}{#TARGET_GROUP_NAME}]</"key>
Note : remove the " in keys part

**Comment by danimas** [comment]
Thanks @MrBal.
I modified the line that you suggest, but i got an another error.

**The section is now like this:**

>\<item_prototype\>
>                             \<name\>ELBv2: {#TARGET_GROUP_LOAD_BALANCER_NAME} target group {#TARGET_GROUP_NAME} total targets\</name\>
>                             \<type\>15\</type\>
>                             \<snmp_community/\>
>                             \<snmp_oid/\>
>                             \<key\>instances[{#TARGET_GROUP_LOAD_BALANCER_NAME}{#TARGET_GROUP_NAME}]\</key\>

**I got the following error:**

> Incorrect trigger expression. Check expression part starting from "{Cloudwatch Template:instances[{#TARGET_GROUP_LOAD_BALANCER_NAME}][{#TARGET_GROUP_NAME}].last()}=-1".

**Comment by MrBal** [comment]
@danimas same error here in zabbix share , maybe solve your problem it's work for me

https://share.zabbix.com/cloud/zabbix-cloudwatch-integration

**Comment by melch700** [comment]
@MrBal and @danimas , removed the square brackets at

<key>instances[{#TARGET_GROUP_LOAD_BALANCER_NAME}][{#TARGET_GROUP_NAME}]</key>

<expression>{Cloudwatch Template:instances[{#TARGET_GROUP_LOAD_BALANCER_NAME}{#TARGET_GROUP_NAME}].last()}=-1</expression>

<expression>{Cloudwatch Template:instances[{#TARGET_GROUP_LOAD_BALANCER_NAME}{#TARGET_GROUP_NAME}].last()}=0</expression>

this worked for me thanks.
