### ISSUE TITLE
Support for ECS?

### ISSUE THREAD

**Issue by aviramartac** [wawastein/zabbix-cloudwatch#4]
Hi,

Does this support discovery and monitoring of ECS instances?
Is it possible to add this?

Thanks

**Comment by wawastein** [comment]
Hi @aviramartac,
This supports anything that can be accessed through Boto3 library. 
However, I don't have access to AWS account with active ECS service, so I cannot write implementation right now. But I can help you with that if you like.

**Comment by aviramartac** [comment]
Hi. thanks for replying.

Just in general, how would you go about starting this? 
I have some knowledge in Python but not too in-depth

**Comment by wawastein** [comment]
I've written a rundown in my blog post: https://awawastuff.wordpress.com/2017/04/13/zabbix-and-cloudwatch-integration/ (see 'How to customize and debug modules')

In short: you need to create new python file for service discovery and populate it with code which will query AWS API and return list of items you want to monitor.

Let me know if I can help further.

**Comment by wawastein** [comment]
For exact metrics you need to review this: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html
It's not ECS API, it's Cloudwatch API, but ECS methods within that API. 
You can open Cloudwatch console and see which metrics you want to see in Zabbix.

**Comment by aviramartac** [comment]
Good stuff man, I'll start working on it and make a pull request when I'm done. Thanks
